/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AbdullakhMyHeader, } from "./components/res/view/s-abdullakh-header/interface/common.interface";
export namespace Components {
    interface MyComponent {
    }
    interface SAbdullakhAppBlog {
        "p": any;
    }
    interface SAbdullakhEvents {
        /**
          * массив компоненту Events
         */
        "events": any[];
        /**
          * заголовок компонента Events
         */
        "eventsTitle": string;
    }
    interface SAbdullakhFooter {
        /**
          * массив для вывода компонентов footer
         */
        "footer": any;
    }
    interface SAbdullakhFooterIconBlock {
        /**
          * массив для вывода компонентов footer
         */
        "arr": any;
    }
    interface SAbdullakhFooterIcons {
        /**
          * массив для выводы иконок
         */
        "arr": any;
    }
    interface SAbdullakhFooterLinks {
        /**
          * массив элементов Sidebar
         */
        "arr": any;
    }
    interface SAbdullakhFooterMenu {
        /**
          * массив элементов Sidebar
         */
        "arr": any;
    }
    interface SAbdullakhHeader {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl": string;
        /**
          * массив меню
         */
        "menu": AbdullakhMyHeader[];
        /**
          * ссылка на изображение логотипа
         */
        "searchSubscribe": any;
        /**
          * массив меню
         */
        "theme": boolean;
    }
    interface SAbdullakhListiner {
        /**
          * массив Listener
         */
        "arr": any;
    }
    interface SAbdullakhListinerForm {
        /**
          * массив Listener
         */
        "arr": any;
    }
    interface SAbdullakhListinerTitle {
        /**
          * массив Listener
         */
        "arr": any;
    }
    interface SAbdullakhMenuItem {
        /**
          * массив меню
         */
        "arr": any;
    }
    interface SAbdullakhNewListiner {
        "newlistner": any[];
    }
    interface SAbdullakhNewPost {
        /**
          * массив newsPost
         */
        "newPost": any[];
        /**
          * текст заголовка
         */
        "newPostTitle": string;
    }
    interface SAbdullakhNewSinglePost {
        /**
          * массив блоков в компоненте newSinglePost
         */
        "arr": any;
    }
    interface SAbdullakhNews {
        /**
          * массив news-main-block
         */
        "news": any[];
        /**
          * ссылка на изображение логотипа
         */
        "newsImg": string;
        /**
          * массив Sidebar
         */
        "sidebar": any[];
    }
    interface SAbdullakhNewsMainBlock {
        /**
          * массив Sidebar
         */
        "arr": any;
    }
    interface SAbdullakhPopularResources {
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAside": any[];
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAsideTitle": string;
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-banner
         */
        "popularBanner": any[];
    }
    interface SAbdullakhPopularResourcesAside {
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "arr": any;
    }
    interface SAbdullakhPopularResourcesBanner {
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-banner
         */
        "arr": any;
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAsideTitle": string;
    }
    interface SAbdullakhSearchSubscribe {
        /**
          * массив меню
         */
        "arr": any;
    }
    interface SAbdullakhSidebar {
        /**
          * массив элементов Sidebar
         */
        "arr": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSAbdullakhAppBlogElement extends Components.SAbdullakhAppBlog, HTMLStencilElement {
    }
    var HTMLSAbdullakhAppBlogElement: {
        prototype: HTMLSAbdullakhAppBlogElement;
        new (): HTMLSAbdullakhAppBlogElement;
    };
    interface HTMLSAbdullakhEventsElement extends Components.SAbdullakhEvents, HTMLStencilElement {
    }
    var HTMLSAbdullakhEventsElement: {
        prototype: HTMLSAbdullakhEventsElement;
        new (): HTMLSAbdullakhEventsElement;
    };
    interface HTMLSAbdullakhFooterElement extends Components.SAbdullakhFooter, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterElement: {
        prototype: HTMLSAbdullakhFooterElement;
        new (): HTMLSAbdullakhFooterElement;
    };
    interface HTMLSAbdullakhFooterIconBlockElement extends Components.SAbdullakhFooterIconBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterIconBlockElement: {
        prototype: HTMLSAbdullakhFooterIconBlockElement;
        new (): HTMLSAbdullakhFooterIconBlockElement;
    };
    interface HTMLSAbdullakhFooterIconsElement extends Components.SAbdullakhFooterIcons, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterIconsElement: {
        prototype: HTMLSAbdullakhFooterIconsElement;
        new (): HTMLSAbdullakhFooterIconsElement;
    };
    interface HTMLSAbdullakhFooterLinksElement extends Components.SAbdullakhFooterLinks, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterLinksElement: {
        prototype: HTMLSAbdullakhFooterLinksElement;
        new (): HTMLSAbdullakhFooterLinksElement;
    };
    interface HTMLSAbdullakhFooterMenuElement extends Components.SAbdullakhFooterMenu, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterMenuElement: {
        prototype: HTMLSAbdullakhFooterMenuElement;
        new (): HTMLSAbdullakhFooterMenuElement;
    };
    interface HTMLSAbdullakhHeaderElement extends Components.SAbdullakhHeader, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeaderElement: {
        prototype: HTMLSAbdullakhHeaderElement;
        new (): HTMLSAbdullakhHeaderElement;
    };
    interface HTMLSAbdullakhListinerElement extends Components.SAbdullakhListiner, HTMLStencilElement {
    }
    var HTMLSAbdullakhListinerElement: {
        prototype: HTMLSAbdullakhListinerElement;
        new (): HTMLSAbdullakhListinerElement;
    };
    interface HTMLSAbdullakhListinerFormElement extends Components.SAbdullakhListinerForm, HTMLStencilElement {
    }
    var HTMLSAbdullakhListinerFormElement: {
        prototype: HTMLSAbdullakhListinerFormElement;
        new (): HTMLSAbdullakhListinerFormElement;
    };
    interface HTMLSAbdullakhListinerTitleElement extends Components.SAbdullakhListinerTitle, HTMLStencilElement {
    }
    var HTMLSAbdullakhListinerTitleElement: {
        prototype: HTMLSAbdullakhListinerTitleElement;
        new (): HTMLSAbdullakhListinerTitleElement;
    };
    interface HTMLSAbdullakhMenuItemElement extends Components.SAbdullakhMenuItem, HTMLStencilElement {
    }
    var HTMLSAbdullakhMenuItemElement: {
        prototype: HTMLSAbdullakhMenuItemElement;
        new (): HTMLSAbdullakhMenuItemElement;
    };
    interface HTMLSAbdullakhNewListinerElement extends Components.SAbdullakhNewListiner, HTMLStencilElement {
    }
    var HTMLSAbdullakhNewListinerElement: {
        prototype: HTMLSAbdullakhNewListinerElement;
        new (): HTMLSAbdullakhNewListinerElement;
    };
    interface HTMLSAbdullakhNewPostElement extends Components.SAbdullakhNewPost, HTMLStencilElement {
    }
    var HTMLSAbdullakhNewPostElement: {
        prototype: HTMLSAbdullakhNewPostElement;
        new (): HTMLSAbdullakhNewPostElement;
    };
    interface HTMLSAbdullakhNewSinglePostElement extends Components.SAbdullakhNewSinglePost, HTMLStencilElement {
    }
    var HTMLSAbdullakhNewSinglePostElement: {
        prototype: HTMLSAbdullakhNewSinglePostElement;
        new (): HTMLSAbdullakhNewSinglePostElement;
    };
    interface HTMLSAbdullakhNewsElement extends Components.SAbdullakhNews, HTMLStencilElement {
    }
    var HTMLSAbdullakhNewsElement: {
        prototype: HTMLSAbdullakhNewsElement;
        new (): HTMLSAbdullakhNewsElement;
    };
    interface HTMLSAbdullakhNewsMainBlockElement extends Components.SAbdullakhNewsMainBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhNewsMainBlockElement: {
        prototype: HTMLSAbdullakhNewsMainBlockElement;
        new (): HTMLSAbdullakhNewsMainBlockElement;
    };
    interface HTMLSAbdullakhPopularResourcesElement extends Components.SAbdullakhPopularResources, HTMLStencilElement {
    }
    var HTMLSAbdullakhPopularResourcesElement: {
        prototype: HTMLSAbdullakhPopularResourcesElement;
        new (): HTMLSAbdullakhPopularResourcesElement;
    };
    interface HTMLSAbdullakhPopularResourcesAsideElement extends Components.SAbdullakhPopularResourcesAside, HTMLStencilElement {
    }
    var HTMLSAbdullakhPopularResourcesAsideElement: {
        prototype: HTMLSAbdullakhPopularResourcesAsideElement;
        new (): HTMLSAbdullakhPopularResourcesAsideElement;
    };
    interface HTMLSAbdullakhPopularResourcesBannerElement extends Components.SAbdullakhPopularResourcesBanner, HTMLStencilElement {
    }
    var HTMLSAbdullakhPopularResourcesBannerElement: {
        prototype: HTMLSAbdullakhPopularResourcesBannerElement;
        new (): HTMLSAbdullakhPopularResourcesBannerElement;
    };
    interface HTMLSAbdullakhSearchSubscribeElement extends Components.SAbdullakhSearchSubscribe, HTMLStencilElement {
    }
    var HTMLSAbdullakhSearchSubscribeElement: {
        prototype: HTMLSAbdullakhSearchSubscribeElement;
        new (): HTMLSAbdullakhSearchSubscribeElement;
    };
    interface HTMLSAbdullakhSidebarElement extends Components.SAbdullakhSidebar, HTMLStencilElement {
    }
    var HTMLSAbdullakhSidebarElement: {
        prototype: HTMLSAbdullakhSidebarElement;
        new (): HTMLSAbdullakhSidebarElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "s-abdullakh-app-blog": HTMLSAbdullakhAppBlogElement;
        "s-abdullakh-events": HTMLSAbdullakhEventsElement;
        "s-abdullakh-footer": HTMLSAbdullakhFooterElement;
        "s-abdullakh-footer-icon-block": HTMLSAbdullakhFooterIconBlockElement;
        "s-abdullakh-footer-icons": HTMLSAbdullakhFooterIconsElement;
        "s-abdullakh-footer-links": HTMLSAbdullakhFooterLinksElement;
        "s-abdullakh-footer-menu": HTMLSAbdullakhFooterMenuElement;
        "s-abdullakh-header": HTMLSAbdullakhHeaderElement;
        "s-abdullakh-listiner": HTMLSAbdullakhListinerElement;
        "s-abdullakh-listiner-form": HTMLSAbdullakhListinerFormElement;
        "s-abdullakh-listiner-title": HTMLSAbdullakhListinerTitleElement;
        "s-abdullakh-menu-item": HTMLSAbdullakhMenuItemElement;
        "s-abdullakh-new-listiner": HTMLSAbdullakhNewListinerElement;
        "s-abdullakh-new-post": HTMLSAbdullakhNewPostElement;
        "s-abdullakh-new-single-post": HTMLSAbdullakhNewSinglePostElement;
        "s-abdullakh-news": HTMLSAbdullakhNewsElement;
        "s-abdullakh-news-main-block": HTMLSAbdullakhNewsMainBlockElement;
        "s-abdullakh-popular-resources": HTMLSAbdullakhPopularResourcesElement;
        "s-abdullakh-popular-resources-aside": HTMLSAbdullakhPopularResourcesAsideElement;
        "s-abdullakh-popular-resources-banner": HTMLSAbdullakhPopularResourcesBannerElement;
        "s-abdullakh-search-subscribe": HTMLSAbdullakhSearchSubscribeElement;
        "s-abdullakh-sidebar": HTMLSAbdullakhSidebarElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface SAbdullakhAppBlog {
        "p"?: any;
    }
    interface SAbdullakhEvents {
        /**
          * массив компоненту Events
         */
        "events"?: any[];
        /**
          * заголовок компонента Events
         */
        "eventsTitle"?: string;
        /**
          * клик по кнопке Read Report в компоненте newSinglePost
         */
        "onClickOnEvents"?: (event: CustomEvent<any>) => void;
        /**
          * клик по в компоненте SAbdullakhNewSinglePost
         */
        "onClickOnNewSinglePost"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhFooter {
        /**
          * массив для вывода компонентов footer
         */
        "footer"?: any;
        /**
          * клик по в компоненте footer
         */
        "onClickOnFooter"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhFooterIconBlock {
        /**
          * массив для вывода компонентов footer
         */
        "arr"?: any;
        /**
          * клик по в компоненте footer
         */
        "onClickOnFooter"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhFooterIcons {
        /**
          * массив для выводы иконок
         */
        "arr"?: any;
        /**
          * массив для выводы иконок
         */
        "onClickOnFooter"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhFooterLinks {
        /**
          * массив элементов Sidebar
         */
        "arr"?: any;
    }
    interface SAbdullakhFooterMenu {
        /**
          * массив элементов Sidebar
         */
        "arr"?: any;
    }
    interface SAbdullakhHeader {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl"?: string;
        /**
          * массив меню
         */
        "menu"?: AbdullakhMyHeader[];
        /**
          * клик по логотипу
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
        /**
          * клик по Switch Theme
         */
        "onClickOnSwitchTheme"?: (event: CustomEvent<any>) => void;
        /**
          * клик по логотипу
         */
        "onClickOnTheme"?: (event: CustomEvent<any>) => void;
        /**
          * ссылка на изображение логотипа
         */
        "searchSubscribe"?: any;
        /**
          * массив меню
         */
        "theme"?: boolean;
    }
    interface SAbdullakhListiner {
        /**
          * массив Listener
         */
        "arr"?: any;
        /**
          * клик по кнопке button в Listiner
         */
        "onClickOnListiner"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhListinerForm {
        /**
          * массив Listener
         */
        "arr"?: any;
        /**
          * клик по кнопке button в Listiner
         */
        "onClickOnListiner"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhListinerTitle {
        /**
          * массив Listener
         */
        "arr"?: any;
        /**
          * клик по кнопке button в Listiner
         */
        "onClickOnListiner"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhMenuItem {
        /**
          * массив меню
         */
        "arr"?: any;
        /**
          * клик по конкретному меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhNewListiner {
        "newlistner"?: any[];
        /**
          * клик в Listiner
         */
        "onClickOnListiner"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhNewPost {
        /**
          * массив newsPost
         */
        "newPost"?: any[];
        /**
          * текст заголовка
         */
        "newPostTitle"?: string;
        /**
          * клик по в компоненте SAbdullakhNewPost
         */
        "onClickNewPost"?: (event: CustomEvent<any>) => void;
        /**
          * клик по в компоненте SAbdullakhNewSinglePost
         */
        "onClickOnNewSinglePost"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhNewSinglePost {
        /**
          * массив блоков в компоненте newSinglePost
         */
        "arr"?: any;
        /**
          * клик по в компоненте SAbdullakhNewSinglePost
         */
        "onClickOnNewSinglePost"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhNews {
        /**
          * массив news-main-block
         */
        "news"?: any[];
        /**
          * ссылка на изображение логотипа
         */
        "newsImg"?: string;
        /**
          * клик по кнопке в компоненте news
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
        /**
          * массив Sidebar
         */
        "sidebar"?: any[];
    }
    interface SAbdullakhNewsMainBlock {
        /**
          * массив Sidebar
         */
        "arr"?: any;
        /**
          * клик по компоненту News
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhPopularResources {
        /**
          * клик по компоненту s-abdullakh-popular-resources
         */
        "onClickOnPopular"?: (event: CustomEvent<any>) => void;
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAside"?: any[];
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAsideTitle"?: string;
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-banner
         */
        "popularBanner"?: any[];
    }
    interface SAbdullakhPopularResourcesAside {
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "arr"?: any;
        /**
          * клик по компоненту  s-abdullakh-s-abdullakh-popular-resources-aside в s-abdullakh-popular-resources
         */
        "onClickOnPopular"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhPopularResourcesBanner {
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-banner
         */
        "arr"?: any;
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnAside"?: (event: CustomEvent<any>) => void;
        /**
          * клик по компоненту  s-abdullakh-s-abdullakh-popular-resources-aside в popular-banner
         */
        "onClickOnPopular"?: (event: CustomEvent<any>) => void;
        /**
          * массив для блоков компонента s-abdullakh-s-abdullakh-popular-resources-aside
         */
        "popularAsideTitle"?: string;
    }
    interface SAbdullakhSearchSubscribe {
        /**
          * массив меню
         */
        "arr"?: any;
        /**
          * клик по конкретному меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhSidebar {
        /**
          * массив элементов Sidebar
         */
        "arr"?: any;
        /**
          * клик по кнопке в компоненте news
         */
        "onClickOnNews"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "s-abdullakh-app-blog": SAbdullakhAppBlog;
        "s-abdullakh-events": SAbdullakhEvents;
        "s-abdullakh-footer": SAbdullakhFooter;
        "s-abdullakh-footer-icon-block": SAbdullakhFooterIconBlock;
        "s-abdullakh-footer-icons": SAbdullakhFooterIcons;
        "s-abdullakh-footer-links": SAbdullakhFooterLinks;
        "s-abdullakh-footer-menu": SAbdullakhFooterMenu;
        "s-abdullakh-header": SAbdullakhHeader;
        "s-abdullakh-listiner": SAbdullakhListiner;
        "s-abdullakh-listiner-form": SAbdullakhListinerForm;
        "s-abdullakh-listiner-title": SAbdullakhListinerTitle;
        "s-abdullakh-menu-item": SAbdullakhMenuItem;
        "s-abdullakh-new-listiner": SAbdullakhNewListiner;
        "s-abdullakh-new-post": SAbdullakhNewPost;
        "s-abdullakh-new-single-post": SAbdullakhNewSinglePost;
        "s-abdullakh-news": SAbdullakhNews;
        "s-abdullakh-news-main-block": SAbdullakhNewsMainBlock;
        "s-abdullakh-popular-resources": SAbdullakhPopularResources;
        "s-abdullakh-popular-resources-aside": SAbdullakhPopularResourcesAside;
        "s-abdullakh-popular-resources-banner": SAbdullakhPopularResourcesBanner;
        "s-abdullakh-search-subscribe": SAbdullakhSearchSubscribe;
        "s-abdullakh-sidebar": SAbdullakhSidebar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-abdullakh-app-blog": LocalJSX.SAbdullakhAppBlog & JSXBase.HTMLAttributes<HTMLSAbdullakhAppBlogElement>;
            "s-abdullakh-events": LocalJSX.SAbdullakhEvents & JSXBase.HTMLAttributes<HTMLSAbdullakhEventsElement>;
            "s-abdullakh-footer": LocalJSX.SAbdullakhFooter & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterElement>;
            "s-abdullakh-footer-icon-block": LocalJSX.SAbdullakhFooterIconBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterIconBlockElement>;
            "s-abdullakh-footer-icons": LocalJSX.SAbdullakhFooterIcons & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterIconsElement>;
            "s-abdullakh-footer-links": LocalJSX.SAbdullakhFooterLinks & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterLinksElement>;
            "s-abdullakh-footer-menu": LocalJSX.SAbdullakhFooterMenu & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterMenuElement>;
            "s-abdullakh-header": LocalJSX.SAbdullakhHeader & JSXBase.HTMLAttributes<HTMLSAbdullakhHeaderElement>;
            "s-abdullakh-listiner": LocalJSX.SAbdullakhListiner & JSXBase.HTMLAttributes<HTMLSAbdullakhListinerElement>;
            "s-abdullakh-listiner-form": LocalJSX.SAbdullakhListinerForm & JSXBase.HTMLAttributes<HTMLSAbdullakhListinerFormElement>;
            "s-abdullakh-listiner-title": LocalJSX.SAbdullakhListinerTitle & JSXBase.HTMLAttributes<HTMLSAbdullakhListinerTitleElement>;
            "s-abdullakh-menu-item": LocalJSX.SAbdullakhMenuItem & JSXBase.HTMLAttributes<HTMLSAbdullakhMenuItemElement>;
            "s-abdullakh-new-listiner": LocalJSX.SAbdullakhNewListiner & JSXBase.HTMLAttributes<HTMLSAbdullakhNewListinerElement>;
            "s-abdullakh-new-post": LocalJSX.SAbdullakhNewPost & JSXBase.HTMLAttributes<HTMLSAbdullakhNewPostElement>;
            "s-abdullakh-new-single-post": LocalJSX.SAbdullakhNewSinglePost & JSXBase.HTMLAttributes<HTMLSAbdullakhNewSinglePostElement>;
            "s-abdullakh-news": LocalJSX.SAbdullakhNews & JSXBase.HTMLAttributes<HTMLSAbdullakhNewsElement>;
            "s-abdullakh-news-main-block": LocalJSX.SAbdullakhNewsMainBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhNewsMainBlockElement>;
            "s-abdullakh-popular-resources": LocalJSX.SAbdullakhPopularResources & JSXBase.HTMLAttributes<HTMLSAbdullakhPopularResourcesElement>;
            "s-abdullakh-popular-resources-aside": LocalJSX.SAbdullakhPopularResourcesAside & JSXBase.HTMLAttributes<HTMLSAbdullakhPopularResourcesAsideElement>;
            "s-abdullakh-popular-resources-banner": LocalJSX.SAbdullakhPopularResourcesBanner & JSXBase.HTMLAttributes<HTMLSAbdullakhPopularResourcesBannerElement>;
            "s-abdullakh-search-subscribe": LocalJSX.SAbdullakhSearchSubscribe & JSXBase.HTMLAttributes<HTMLSAbdullakhSearchSubscribeElement>;
            "s-abdullakh-sidebar": LocalJSX.SAbdullakhSidebar & JSXBase.HTMLAttributes<HTMLSAbdullakhSidebarElement>;
        }
    }
}
