/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AbdullakhMyHeader, } from "./components/res/view/my-header/interface/common.interface";
export namespace Components {
    interface AppBlog {
        "p": any;
    }
    interface EventsA {
        "events": any[];
    }
    interface FooterA {
    }
    interface MenuItem {
        /**
          * массив меню
         */
        "arr": any;
    }
    interface MyComponent {
    }
    interface MyHeader {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl": string;
        /**
          * массив меню
         */
        "menu": AbdullakhMyHeader[];
        /**
          * ссылка на изображение логотипа
         */
        "subscribeText": string;
    }
    interface NewListiner {
        "newlistner": any[];
    }
    interface NewPost {
        /**
          * массив Sidebar
         */
        "newPost": any[];
    }
    interface NewSinglePost {
        "f": string;
        /**
          * массив блоков в компоненте newSinglePost
         */
        "newPost": any[];
    }
    interface NewsA {
        /**
          * массив Sidebar
         */
        "sidebar": any[];
    }
    interface PopularResources {
        /**
          * массив для блоков компонента popular-resources-aside
         */
        "popularAside": any[];
    }
    interface PopularResourcesAside {
        /**
          * массив для блоков компонента popular-resources-aside
         */
        "popularAside": any[];
    }
    interface SidebarA {
        /**
          * путь url для изображения Sidebar
         */
        "arr": any;
    }
}
declare global {
    interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {
    }
    var HTMLAppBlogElement: {
        prototype: HTMLAppBlogElement;
        new (): HTMLAppBlogElement;
    };
    interface HTMLEventsAElement extends Components.EventsA, HTMLStencilElement {
    }
    var HTMLEventsAElement: {
        prototype: HTMLEventsAElement;
        new (): HTMLEventsAElement;
    };
    interface HTMLFooterAElement extends Components.FooterA, HTMLStencilElement {
    }
    var HTMLFooterAElement: {
        prototype: HTMLFooterAElement;
        new (): HTMLFooterAElement;
    };
    interface HTMLMenuItemElement extends Components.MenuItem, HTMLStencilElement {
    }
    var HTMLMenuItemElement: {
        prototype: HTMLMenuItemElement;
        new (): HTMLMenuItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {
    }
    var HTMLMyHeaderElement: {
        prototype: HTMLMyHeaderElement;
        new (): HTMLMyHeaderElement;
    };
    interface HTMLNewListinerElement extends Components.NewListiner, HTMLStencilElement {
    }
    var HTMLNewListinerElement: {
        prototype: HTMLNewListinerElement;
        new (): HTMLNewListinerElement;
    };
    interface HTMLNewPostElement extends Components.NewPost, HTMLStencilElement {
    }
    var HTMLNewPostElement: {
        prototype: HTMLNewPostElement;
        new (): HTMLNewPostElement;
    };
    interface HTMLNewSinglePostElement extends Components.NewSinglePost, HTMLStencilElement {
    }
    var HTMLNewSinglePostElement: {
        prototype: HTMLNewSinglePostElement;
        new (): HTMLNewSinglePostElement;
    };
    interface HTMLNewsAElement extends Components.NewsA, HTMLStencilElement {
    }
    var HTMLNewsAElement: {
        prototype: HTMLNewsAElement;
        new (): HTMLNewsAElement;
    };
    interface HTMLPopularResourcesElement extends Components.PopularResources, HTMLStencilElement {
    }
    var HTMLPopularResourcesElement: {
        prototype: HTMLPopularResourcesElement;
        new (): HTMLPopularResourcesElement;
    };
    interface HTMLPopularResourcesAsideElement extends Components.PopularResourcesAside, HTMLStencilElement {
    }
    var HTMLPopularResourcesAsideElement: {
        prototype: HTMLPopularResourcesAsideElement;
        new (): HTMLPopularResourcesAsideElement;
    };
    interface HTMLSidebarAElement extends Components.SidebarA, HTMLStencilElement {
    }
    var HTMLSidebarAElement: {
        prototype: HTMLSidebarAElement;
        new (): HTMLSidebarAElement;
    };
    interface HTMLElementTagNameMap {
        "app-blog": HTMLAppBlogElement;
        "events-a": HTMLEventsAElement;
        "footer-a": HTMLFooterAElement;
        "menu-item": HTMLMenuItemElement;
        "my-component": HTMLMyComponentElement;
        "my-header": HTMLMyHeaderElement;
        "new-listiner": HTMLNewListinerElement;
        "new-post": HTMLNewPostElement;
        "new-single-post": HTMLNewSinglePostElement;
        "news-a": HTMLNewsAElement;
        "popular-resources": HTMLPopularResourcesElement;
        "popular-resources-aside": HTMLPopularResourcesAsideElement;
        "sidebar-a": HTMLSidebarAElement;
    }
}
declare namespace LocalJSX {
    interface AppBlog {
        "p"?: any;
    }
    interface EventsA {
        "events"?: any[];
        /**
          * клик по кнопке Read Report в компоненте newSinglePost
         */
        "onClickReadReportOnNewSinglePost"?: (event: CustomEvent<any>) => void;
    }
    interface FooterA {
    }
    interface MenuItem {
        /**
          * массив меню
         */
        "arr"?: any;
        /**
          * клик по конкретному меню
         */
        "onClickOnMenu"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
    }
    interface MyHeader {
        /**
          * ссылка на изображение логотипа
         */
        "logoUrl"?: string;
        /**
          * массив меню
         */
        "menu"?: AbdullakhMyHeader[];
        /**
          * клик по конкретному меню
         */
        "onClickOnMenu"?: (event: CustomEvent<AbdullakhMyHeader>) => void;
        /**
          * клик по кнопке подписаться
         */
        "onClickOnSubscribeButton"?: (event: CustomEvent<any>) => void;
        /**
          * клик по логотипу
         */
        "onClickToLogo"?: (event: CustomEvent<any>) => void;
        /**
          * ссылка на изображение логотипа
         */
        "subscribeText"?: string;
    }
    interface NewListiner {
        "newlistner"?: any[];
    }
    interface NewPost {
        /**
          * массив Sidebar
         */
        "newPost"?: any[];
        /**
          * клик по кнопке Read Report в компоненте newSinglePost
         */
        "onClickNewPost"?: (event: CustomEvent<any>) => void;
    }
    interface NewSinglePost {
        "f"?: string;
        /**
          * массив блоков в компоненте newSinglePost
         */
        "newPost"?: any[];
        /**
          * клик по кнопке Read Report в компоненте newSinglePost
         */
        "onClickNewPost"?: (event: CustomEvent<any>) => void;
    }
    interface NewsA {
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnNewsButton"?: (event: CustomEvent<any>) => void;
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnSidebar"?: (event: CustomEvent<any>) => void;
        /**
          * массив Sidebar
         */
        "sidebar"?: any[];
    }
    interface PopularResources {
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnAside"?: (event: CustomEvent<any>) => void;
        /**
          * массив для блоков компонента popular-resources-aside
         */
        "popularAside"?: any[];
    }
    interface PopularResourcesAside {
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnAside"?: (event: CustomEvent<any>) => void;
        /**
          * массив для блоков компонента popular-resources-aside
         */
        "popularAside"?: any[];
    }
    interface SidebarA {
        /**
          * путь url для изображения Sidebar
         */
        "arr"?: any;
        /**
          * клик по кнопке Read Report в Sidebar
         */
        "onClickOnSidebar"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-blog": AppBlog;
        "events-a": EventsA;
        "footer-a": FooterA;
        "menu-item": MenuItem;
        "my-component": MyComponent;
        "my-header": MyHeader;
        "new-listiner": NewListiner;
        "new-post": NewPost;
        "new-single-post": NewSinglePost;
        "news-a": NewsA;
        "popular-resources": PopularResources;
        "popular-resources-aside": PopularResourcesAside;
        "sidebar-a": SidebarA;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-blog": LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
            "events-a": LocalJSX.EventsA & JSXBase.HTMLAttributes<HTMLEventsAElement>;
            "footer-a": LocalJSX.FooterA & JSXBase.HTMLAttributes<HTMLFooterAElement>;
            "menu-item": LocalJSX.MenuItem & JSXBase.HTMLAttributes<HTMLMenuItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-header": LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
            "new-listiner": LocalJSX.NewListiner & JSXBase.HTMLAttributes<HTMLNewListinerElement>;
            "new-post": LocalJSX.NewPost & JSXBase.HTMLAttributes<HTMLNewPostElement>;
            "new-single-post": LocalJSX.NewSinglePost & JSXBase.HTMLAttributes<HTMLNewSinglePostElement>;
            "news-a": LocalJSX.NewsA & JSXBase.HTMLAttributes<HTMLNewsAElement>;
            "popular-resources": LocalJSX.PopularResources & JSXBase.HTMLAttributes<HTMLPopularResourcesElement>;
            "popular-resources-aside": LocalJSX.PopularResourcesAside & JSXBase.HTMLAttributes<HTMLPopularResourcesAsideElement>;
            "sidebar-a": LocalJSX.SidebarA & JSXBase.HTMLAttributes<HTMLSidebarAElement>;
        }
    }
}
